DELETE FROM iam.permissions WHERE code IN (
    'USERS_READ', 'USERS_MANAGE', 'ROLES_MANAGE', 'BRAND_CONFIGURATION_MANAGE',
    'BRANCHES_MANAGE', 'FLEET_MANAGE', 'CATALOG_MANAGE', 'RESERVATIONS_READ',
    'RESERVATIONS_MANAGE', 'CONTRACTS_MANAGE', 'PAYMENTS_MANAGE', 'SUPPORT_MANAGE',
    'REPORTS_READ', 'AUDIT_READ'
);
