DELETE FROM iam.security_configurations
WHERE config_key IN (
    'MAX_LOGIN_ATTEMPTS',
    'ACCOUNT_LOCKOUT_MINUTES',
    'MFA_REQUIRED_FOR_ADMINS',
    'SESSION_IDLE_TIMEOUT_MINUTES',
    'PASSWORD_RESET_TOKEN_EXPIRATION_MINUTES'
);
