CREATE TABLE fleet.vehicles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    plate VARCHAR(10) NOT NULL,
    vin VARCHAR(17) NOT NULL,
    brand_id UUID NOT NULL,
    category_id UUID NOT NULL,
    transmission_type_id UUID NOT NULL,
    fuel_type_id UUID NOT NULL,
    status_id UUID NOT NULL,
    current_branch_id UUID NOT NULL,
    model VARCHAR(100) NOT NULL,
    year SMALLINT NOT NULL,
    color VARCHAR(50),
    passenger_capacity SMALLINT NOT NULL,
    doors_count SMALLINT,
    trunk_capacity_liters INTEGER,
    mileage INTEGER NOT NULL DEFAULT 0,
    daily_rate NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    main_image_url VARCHAR(2048),
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_vehicles_plate UNIQUE (plate),
    CONSTRAINT uq_vehicles_vin UNIQUE (vin),
    CONSTRAINT fk_vehicles_brand FOREIGN KEY (brand_id) REFERENCES fleet.vehicle_brands (id),
    CONSTRAINT fk_vehicles_category FOREIGN KEY (category_id) REFERENCES fleet.vehicle_categories (id),
    CONSTRAINT fk_vehicles_transmission_type FOREIGN KEY (transmission_type_id) REFERENCES fleet.transmission_types (id),
    CONSTRAINT fk_vehicles_fuel_type FOREIGN KEY (fuel_type_id) REFERENCES fleet.fuel_types (id),
    CONSTRAINT fk_vehicles_status FOREIGN KEY (status_id) REFERENCES fleet.vehicle_statuses (id),
    CONSTRAINT fk_vehicles_current_branch FOREIGN KEY (current_branch_id) REFERENCES location.branches (id),
    CONSTRAINT chk_vehicles_plate_not_blank CHECK (btrim(plate) <> ''),
    CONSTRAINT chk_vehicles_vin_not_blank CHECK (btrim(vin) <> ''),
    CONSTRAINT chk_vehicles_model_not_blank CHECK (btrim(model) <> ''),
    CONSTRAINT chk_vehicles_year CHECK (year BETWEEN 1900 AND 2100),
    CONSTRAINT chk_vehicles_passenger_capacity CHECK (passenger_capacity > 0),
    CONSTRAINT chk_vehicles_mileage CHECK (mileage >= 0),
    CONSTRAINT chk_vehicles_daily_rate CHECK (daily_rate >= 0)
);
