CREATE TABLE rental.reservations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(30) NOT NULL,
    customer_id UUID NOT NULL,
    vehicle_id UUID NOT NULL,
    status_id UUID NOT NULL,
    insurance_coverage_id UUID NOT NULL,
    mileage_plan_id UUID NOT NULL,
    cash_payment_branch_id UUID,
    pickup_date TIMESTAMPTZ NOT NULL,
    return_date TIMESTAMPTZ NOT NULL,
    daily_rate NUMERIC(12, 2) NOT NULL,
    total_estimated NUMERIC(12, 2) NOT NULL,
    cash_payment_code VARCHAR(30),
    cash_payment_expires_at TIMESTAMPTZ,
    blocks_availability BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_reservations_code UNIQUE (code),
    CONSTRAINT uq_reservations_cash_payment_code UNIQUE (cash_payment_code),
    CONSTRAINT fk_reservations_customer FOREIGN KEY (customer_id) REFERENCES iam.users (id),
    CONSTRAINT fk_reservations_vehicle FOREIGN KEY (vehicle_id) REFERENCES fleet.vehicles (id),
    CONSTRAINT fk_reservations_status FOREIGN KEY (status_id) REFERENCES rental.reservation_statuses (id),
    CONSTRAINT fk_reservations_insurance_coverage FOREIGN KEY (insurance_coverage_id) REFERENCES catalog.insurance_coverages (id),
    CONSTRAINT fk_reservations_mileage_plan FOREIGN KEY (mileage_plan_id) REFERENCES catalog.mileage_plans (id),
    CONSTRAINT fk_reservations_cash_payment_branch FOREIGN KEY (cash_payment_branch_id) REFERENCES location.branches (id),
    CONSTRAINT chk_reservations_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT chk_reservations_period CHECK (return_date > pickup_date),
    CONSTRAINT chk_reservations_daily_rate_nonnegative CHECK (daily_rate >= 0),
    CONSTRAINT chk_reservations_total_estimated_nonnegative CHECK (total_estimated >= 0),
    CONSTRAINT chk_reservations_cash_payment_code_not_blank CHECK (cash_payment_code IS NULL OR btrim(cash_payment_code) <> '')
);
